<a href="https://colab.research.google.com/github/sethkipsangmutuba/Data-Visualization/blob/main/Session_A7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Fancy Indexing
##Seth Kipsang

### Exploring Fancy Indexing

### Combined Indexing

### Example: Selecting Random Points

### Modifying Values with Fancy Indexing

### Example: Binning Data

## Fancy Indexing

In previous sections, we accessed parts of arrays using simple indexing (single values), slicing (ranges of values), and Boolean masking (filter-based selection). Fancy indexing extends this idea by using arrays of indices instead of single values. This allows direct selection of multiple, non-contiguous elements and enables more flexible and powerful extraction or modification of array subsets.

##7.1) Exploring Fancy Indexing

Fancy indexing uses arrays of indices to access multiple elements at once.

Instead of single values or slices, you pass index lists or arrays to select elements.

The result depends on the shape of the index array, not the original array.

It works in multiple dimensions by pairing row and column index arrays element-wise.

With broadcasting, index arrays can combine to produce grid-like selections.

Key idea: fancy indexing enables flexible, non-contiguous selection of array elements efficiently.

In [485]:
import numpy as np

# Iris dataset

X = iris_df.iloc[:, :4].to_numpy()

# 1. 1D fancy indexing (arbitrary element selection)

indices = np.array([0, 5, 10, 20, 30])

selected_rows = X[indices]

print("Selected rows shape:", selected_rows.shape)
print("Selected rows:\n", selected_rows)


Selected rows shape: (5, 4)
Selected rows:
 [[5.1 3.5 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [5.4 3.7 1.5 0.2]
 [5.4 3.4 1.7 0.2]
 [4.8 3.1 1.6 0.2]]


In [486]:
# 2. Column selection via fancy indexing

col_indices = np.array([0, 2, 3])  # select specific features

selected_cols = X[:, col_indices]

print("\nSelected columns shape:", selected_cols.shape)



Selected columns shape: (150, 3)


In [487]:
# 3. Row + column fancy indexing (paired indexing)

row_idx = np.array([0, 1, 2, 3])
col_idx = np.array([3, 2, 1, 0])

paired_selection = X[row_idx, col_idx]

print("\nPaired indexing result:", paired_selection)



Paired indexing result: [0.2 1.4 3.2 4.6]


In [488]:
# 4. Grid-style selection using broadcasting

row_grid = np.array([0, 1, 2])[:, np.newaxis]
col_grid = np.array([0, 1, 2])

grid_selection = X[row_grid, col_grid]

print("\nGrid selection shape:", grid_selection.shape)



Grid selection shape: (3, 3)


In [489]:
# 5. Non-contiguous random sampling

random_idx = np.random.RandomState(42).choice(150, size=10, replace=False)

random_sample = X[random_idx]

print("\nRandom sample shape:", random_sample.shape)


Random sample shape: (10, 4)


##7.2) Combined Indexing

Fancy indexing can be combined with simple indexing, slicing, and masking to create more flexible selections.

You can mix:

- Simple index + fancy index to reorder elements  
- Slicing + fancy index to select submatrices with custom columns  
- Boolean masks + fancy index to filter specific columns or rows  

These combinations allow highly flexible data extraction and modification.

---

## Example: Selecting Random Points

Fancy indexing is commonly used to select random subsets of data points from a dataset. For a matrix representing points in a 2D space, random indices are generated and used to extract a subset of rows.

This is useful for sampling and splitting data in statistical analysis and model evaluation.

---

## Key idea

Combining indexing methods enables powerful, flexible data selection strategies.

In [490]:
import numpy as np

# Iris dataset

X = iris_df.iloc[:, :4].to_numpy()

# 1. Simple index + fancy index (reordering rows)

simple_idx = 2
fancy_idx = np.array([0, 5, 10, 15])

reordered = X[[simple_idx, *fancy_idx]]

print("Reordered rows shape:", reordered.shape)


Reordered rows shape: (5, 4)


In [491]:
# 2. Slicing + fancy indexing (custom column selection)

subset = X[:, 1:4]                 # slice first
fancy_cols = np.array([0, 2])      # within subset

combined_cols = subset[:, fancy_cols]

print("\nSlicing + fancy indexing shape:", combined_cols.shape)



Slicing + fancy indexing shape: (150, 2)


In [492]:
# 3. Boolean mask + fancy indexing (filtered + selected rows)

mask = X[:, 0] > 5.5              # filter condition
filtered = X[mask]                # step 1: masking

fancy_rows = np.array([0, 2, 4])  # step 2: fancy selection

final_selection = filtered[fancy_rows]

print("\nMask + fancy indexing shape:", final_selection.shape)



Mask + fancy indexing shape: (3, 4)


In [493]:
# 4. Random sampling using fancy indexing

rng = np.random.RandomState(42)

random_indices = rng.choice(X.shape[0], size=10, replace=False)

random_sample = X[random_indices]

print("\nRandom sample shape:", random_sample.shape)
print("Random sample:\n", random_sample)



Random sample shape: (10, 4)
Random sample:
 [[6.1 2.8 4.7 1.2]
 [5.7 3.8 1.7 0.3]
 [7.7 2.6 6.9 2.3]
 [6.  2.9 4.5 1.5]
 [6.8 2.8 4.8 1.4]
 [5.4 3.4 1.5 0.4]
 [5.6 2.9 3.6 1.3]
 [6.9 3.1 5.1 2.3]
 [6.2 2.2 4.5 1.5]
 [5.8 2.7 3.9 1.2]]


In [494]:
# 5. Mixed row/column indexing (advanced selection)

row_idx = np.array([0, 1, 2])
col_slice = slice(1, 3)

mixed_selection = X[row_idx][:, col_slice]

print("\nMixed indexing shape:", mixed_selection.shape)


Mixed indexing shape: (3, 2)


## Modifying Values with Fancy Indexing

Fancy indexing can also be used to change array values directly by assigning to selected indices.

You can:

- Assign a single value to multiple indexed positions  
- Use assignment operators (e.g., `+=`, `-=`) on selected indices  

However, repeated indices can produce unexpected behavior because assignments are applied in a single step, not sequentially.

To ensure repeated updates work correctly (i.e., applying an operation multiple times per index), NumPy provides ufunc methods like `at()`, which perform in-place updates per occurrence.

---

## Example: Binning Data

Fancy indexing can be used to build histograms by:

- Defining bin edges  
- Finding bin positions using search operations  
- Using `ufunc.at()` to increment counts efficiently  

This reproduces histogram-like behavior manually and helps illustrate how binning works internally.

In practice, built-in functions like `histogram` are preferred because they are optimized and more flexible.

---

## Key idea

Fancy indexing allows both direct modification of selected elements and low-level control over aggregation-like operations.

In [495]:
import numpy as np

# Iris dataset

X = iris_df.iloc[:, :4].to_numpy()

# Work on a copy to preserve original
x = X[:, 0].copy()

# 1. Assign single value to multiple indices

idx = np.array([0, 5, 10, 15])

x[idx] = 100

print("After assignment (first 20):", x[:20])


After assignment (first 20): [100.    4.9   4.7   4.6   5.  100.    4.6   5.    4.4   4.9 100.    4.8
   4.8   4.3   5.8 100.    5.4   5.1   5.7   5.1]


In [496]:
# 2. Augmented assignment (+=)

x2 = X[:, 0].copy()

x2[idx] += 10

print("\nAfter += (first 20):", x2[:20])



After += (first 20): [15.1  4.9  4.7  4.6  5.  15.4  4.6  5.   4.4  4.9 15.4  4.8  4.8  4.3
  5.8 15.7  5.4  5.1  5.7  5.1]


In [497]:
# 3. Repeated indices problem

x3 = X[:, 0].copy()

repeated_idx = np.array([0, 0, 0, 1, 1])

x3[repeated_idx] += 1

print("\nRepeated index result:", x3[:5])


Repeated index result: [6.1 5.9 4.7 4.6 5. ]


Binning

In [498]:
data = X[:, 0]  # sepal length

# Define bins
bins = np.linspace(data.min(), data.max(), 6)

# Find bin indices
bin_idx = np.searchsorted(bins, data) - 1

# Initialize counts
counts = np.zeros(len(bins) - 1, dtype=int)

# Accumulate counts
np.add.at(counts, bin_idx, 1)

print("Manual histogram counts:", counts)
print("Bins:", bins)

Manual histogram counts: [31 41 42 24 12]
Bins: [4.3  5.02 5.74 6.46 7.18 7.9 ]
