<a href="https://colab.research.google.com/github/sethkipsangmutuba/Data-Visualization/blob/main/Session_A2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#The Basics of NumPy Arrays

##Seth Kipsang

### NumPy Array Attributes

### Array Indexing: Accessing Single Elements

### Array Slicing: Accessing Subarrays

### Array Concatenation and Splitting

##2).  The Basics of NumPy Arrays

NumPy arrays form the core abstraction for numerical computation in Python, and most data manipulation workflows directly or indirectly (including tools like Pandas) are built upon them. Understanding array operations is therefore essential for efficient data handling in scientific and analytical contexts.

The fundamental manipulations of NumPy arrays can be organized into five core categories:

**Array attributes:** These describe structural properties of an array, such as its dimensionality, shape, total size, memory usage, and data type. Together, they define how the array is stored and interpreted.

**Array indexing:** This refers to accessing or modifying individual elements within an array using position-based referencing. It forms the most granular level of data interaction.

**Array slicing:** This extends indexing to extract sub-regions of an array. It allows selection of contiguous or patterned subsets without copying data, enabling efficient views into large datasets.

**Array reshaping:** Arrays can be reorganized into different dimensions or structures without altering their underlying data. This is especially important when aligning data for computation or modeling.

**Array joining and splitting:** Multiple arrays can be combined into a single structure or decomposed into smaller components. These operations support modular data construction and decomposition of complex datasets.

Collectively, these operations form the foundational toolkit for working with structured numerical data in Python. Mastery of them is essential, as they underpin higher-level analytical techniques used throughout data science, statistical modeling, and machine learning workflows.

##2.1) NumPy Array Attributes

NumPy arrays carry rich structural metadata that describes how data is stored and organized in memory. To illustrate this, we begin by generating reproducible random arrays of increasing dimensionality: a 1D vector, a 2D matrix, and a 3D tensor. Fixing the random seed ensures consistent outputs across runs, which is essential for scientific reproducibility.

Once created, arrays expose key attributes that describe their internal structure:

**ndim:** The number of dimensions (or axes) of the array. This distinguishes vectors, matrices, and higher-order tensors.

**shape:** A tuple describing the size of the array along each dimension, providing its structural layout.

**size:** The total number of elements contained in the array, independent of dimensional structure.

In addition to structural properties, arrays also expose low-level memory characteristics:

**dtype:** The data type of the elements, determining numerical precision and storage format.

**itemsize:** The memory footprint (in bytes) of a single element.

**nbytes:** The total memory consumed by the array.

A fundamental identity holds that total memory usage equals element size multiplied by number of elements, reinforcing the tight coupling between structure and memory representation in NumPy.

Together, these attributes provide a foundational understanding of how arrays are organized, stored, and interpreted critical for efficient computation in data science and statistical analytics.

In [242]:
# Reproducibility

np.random.seed(42)

# 1. 1D Array (Vector)

vec = np.random.rand(5)
vec


array([0.37454012, 0.95071431, 0.73199394, 0.59865848, 0.15601864])

In [243]:
# 2. 2D Array (Matrix)

mat = np.random.rand(3, 4)
mat

array([[0.15599452, 0.05808361, 0.86617615, 0.60111501],
       [0.70807258, 0.02058449, 0.96990985, 0.83244264],
       [0.21233911, 0.18182497, 0.18340451, 0.30424224]])

In [244]:
# 3. 3D Array (Tensor)

tensor = np.random.rand(2, 3, 4)
tensor

array([[[0.52475643, 0.43194502, 0.29122914, 0.61185289],
        [0.13949386, 0.29214465, 0.36636184, 0.45606998],
        [0.78517596, 0.19967378, 0.51423444, 0.59241457]],

       [[0.04645041, 0.60754485, 0.17052412, 0.06505159],
        [0.94888554, 0.96563203, 0.80839735, 0.30461377],
        [0.09767211, 0.68423303, 0.44015249, 0.12203823]]])

In [245]:
# Attribute Inspection

def inspect_array(name, arr):
    print(f"\n--- {name} ---")
    print("Array:\n", arr)
    print("ndim:", arr.ndim)
    print("shape:", arr.shape)
    print("size:", arr.size)
    print("dtype:", arr.dtype)
    print("itemsize (bytes):", arr.itemsize)
    print("nbytes (total memory):", arr.nbytes)

inspect_array("1D Vector", vec)
inspect_array("2D Matrix", mat)
inspect_array("3D Tensor", tensor)


--- 1D Vector ---
Array:
 [0.37454012 0.95071431 0.73199394 0.59865848 0.15601864]
ndim: 1
shape: (5,)
size: 5
dtype: float64
itemsize (bytes): 8
nbytes (total memory): 40

--- 2D Matrix ---
Array:
 [[0.15599452 0.05808361 0.86617615 0.60111501]
 [0.70807258 0.02058449 0.96990985 0.83244264]
 [0.21233911 0.18182497 0.18340451 0.30424224]]
ndim: 2
shape: (3, 4)
size: 12
dtype: float64
itemsize (bytes): 8
nbytes (total memory): 96

--- 3D Tensor ---
Array:
 [[[0.52475643 0.43194502 0.29122914 0.61185289]
  [0.13949386 0.29214465 0.36636184 0.45606998]
  [0.78517596 0.19967378 0.51423444 0.59241457]]

 [[0.04645041 0.60754485 0.17052412 0.06505159]
  [0.94888554 0.96563203 0.80839735 0.30461377]
  [0.09767211 0.68423303 0.44015249 0.12203823]]]
ndim: 3
shape: (2, 3, 4)
size: 24
dtype: float64
itemsize (bytes): 8
nbytes (total memory): 192


In [246]:
# 4. Memory Identity Check

print("\n--- Memory Identity ---")
print("vec: size × itemsize =", vec.size * vec.itemsize)
print("nbytes =", vec.nbytes)
print("Consistency check:", vec.size * vec.itemsize == vec.nbytes)


--- Memory Identity ---
vec: size × itemsize = 40
nbytes = 40
Consistency check: True


##2.2).  Array Indexing: Accessing Single Elements

Array indexing in NumPy closely mirrors Python’s native list indexing, making it intuitive for users familiar with standard Python data structures. In a one-dimensional array, elements are accessed using zero-based indexing, where the position of an element determines its retrieval.

Negative indexing is also supported, allowing access from the end of the array. This provides a flexible way to reference the last elements without explicitly computing their positions.

In multidimensional arrays, indexing extends naturally by using a comma-separated tuple of indices. Each index corresponds to a specific dimension, enabling precise access to individual elements within matrices or higher-dimensional structures.

NumPy also allows modification of elements through direct assignment using index notation. However, unlike Python lists, NumPy arrays enforce a fixed data type. This means that if a value of a different type is assigned, it will be coerced to the array’s original type, potentially resulting in truncation or loss of precision. This behavior reflects NumPy’s emphasis on type consistency and computational efficiency in numerical operations.

In [247]:
import numpy as np

# Create NumPy array from Iris data
arr = iris_df.to_numpy()


# 1. One-Dimensional Indexing

vec = arr[:, 0]  # first feature column

print("First element:", vec[0])
print("Fifth element:", vec[4])


# Negative indexing

print("Last element:", vec[-1])
print("Second last element:", vec[-2])


First element: 999.0
Fifth element: 5.0
Last element: 5.9
Second last element: 6.2


In [248]:
# 2. Two-Dimensional Indexing

print("\nMatrix element (row 0, col 1):", arr[0, 1])
print("Matrix element (row 10, col 3):", arr[10, 3])



Matrix element (row 0, col 1): 3.5
Matrix element (row 10, col 3): 0.2


In [249]:
# 3. Direct Modification

print("\nOriginal value:", arr[0, 0])

arr[0, 0] = 999.99
print("After assignment:", arr[0, 0])



Original value: 999.0
After assignment: 999.99


In [250]:
# 4. Type Coercion Behavior

print("\nArray dtype:", arr.dtype)

# Assign a string to numeric array (forced coercion attempt)
arr[0, 0] = "100"

print("After string assignment:", arr[0, 0])
print("dtype remains:", arr.dtype)



Array dtype: float64
After string assignment: 100.0
dtype remains: float64


In [251]:
# 5. Negative indexing in matrix form

print("\nLast row:", arr[-1])
print("Last element of last row:", arr[-1, -1])


Last row: [5.9 3.  5.1 1.8]
Last element of last row: 1.8


##2.3) Array Slicing: Accessing Subarrays

Array slicing in NumPy extends the concept of indexing to allow extraction of subsets of data from larger arrays. It uses a colon-based notation of the form:

x[start:stop:step]

If any parameter is omitted, NumPy applies default values: starting from the beginning of the dimension, ending at the last element, and using a step of one.

---

### One-dimensional slicing

In a 1D array, slicing enables extraction of continuous segments, such as the first elements, trailing elements, or a middle portion. Step size can also be adjusted to skip elements, enabling patterned selection. A negative step reverses traversal order, providing a compact way to invert arrays or extract elements in reverse sequence.

---

### Multidimensional slicing

In higher-dimensional arrays, slicing operates independently along each axis using comma-separated notation. This allows precise extraction of rows, columns, or submatrices. Entire rows or columns can also be accessed using a single colon for that dimension.

---

### Views vs copies

A critical conceptual distinction is that NumPy slicing generally returns a view, not a copy. This means modifications to a sliced subarray can affect the original dataset because both share the same underlying memory buffer. This design significantly improves efficiency for large-scale computation.

However, when independent data is required, an explicit copy operation must be used. This ensures that changes to the subarray do not propagate back to the original array.

---

Slicing is a powerful mechanism that balances expressive data access with memory-efficient computation, making it essential for high-performance numerical analysis.

In [252]:
import numpy as np

# -----------------------------
arr = iris_df.to_numpy()

# 1. One-Dimensional Slicing

vec = arr[:, 0]  # first feature column

print("Original vector (first 10):", vec[:10])

print("First 5 elements:", vec[:5])
print("Last 5 elements:", vec[-5:])
print("Middle slice (5 to 10):", vec[5:10])

# Step slicing
print("Every 2nd element:", vec[::2])

# Reversing array
print("Reversed vector:", vec[::-1][:10])  # show only first 10 reversed


Original vector (first 10): [100.    4.9   4.7   4.6   5.    5.4   4.6   5.    4.4   4.9]
First 5 elements: [100.    4.9   4.7   4.6   5. ]
Last 5 elements: [6.7 6.3 6.5 6.2 5.9]
Middle slice (5 to 10): [5.4 4.6 5.  4.4 4.9]
Every 2nd element: [100.    4.7   5.    4.6   4.4   5.4   4.8   5.8   5.4   5.7   5.4   4.6
   4.8   5.    5.2   4.8   5.2   4.9   5.5   4.4   5.    4.4   5.1   5.1
   5.3   7.    6.9   6.5   6.3   6.6   5.    6.    5.6   5.6   6.2   5.9
   6.3   6.4   6.8   6.    5.5   5.8   5.4   6.7   5.6   5.5   5.8   5.6
   5.7   5.1   6.3   7.1   6.5   4.9   6.7   6.5   6.8   5.8   6.5   7.7
   6.9   7.7   6.7   6.2   6.4   7.4   6.4   6.1   6.3   6.    6.7   5.8
   6.7   6.3   6.2]
Reversed vector: [5.9 6.2 6.5 6.3 6.7 6.7 6.8 5.8 6.9 6.7]


In [253]:
# 2. Multidimensional Slicing

print("\nFirst 3 rows, all columns:\n", arr[:3, :])
print("\nAll rows, first 2 columns:\n", arr[:, :2])
print("\nSubmatrix (rows 5-10, cols 1-3):\n", arr[5:10, 1:3])



First 3 rows, all columns:
 [[100.    3.5   1.4   0.2]
 [  4.9   3.    1.4   0.2]
 [  4.7   3.2   1.3   0.2]]

All rows, first 2 columns:
 [[100.    3.5]
 [  4.9   3. ]
 [  4.7   3.2]
 [  4.6   3.1]
 [  5.    3.6]
 [  5.4   3.9]
 [  4.6   3.4]
 [  5.    3.4]
 [  4.4   2.9]
 [  4.9   3.1]
 [  5.4   3.7]
 [  4.8   3.4]
 [  4.8   3. ]
 [  4.3   3. ]
 [  5.8   4. ]
 [  5.7   4.4]
 [  5.4   3.9]
 [  5.1   3.5]
 [  5.7   3.8]
 [  5.1   3.8]
 [  5.4   3.4]
 [  5.1   3.7]
 [  4.6   3.6]
 [  5.1   3.3]
 [  4.8   3.4]
 [  5.    3. ]
 [  5.    3.4]
 [  5.2   3.5]
 [  5.2   3.4]
 [  4.7   3.2]
 [  4.8   3.1]
 [  5.4   3.4]
 [  5.2   4.1]
 [  5.5   4.2]
 [  4.9   3.1]
 [  5.    3.2]
 [  5.5   3.5]
 [  4.9   3.6]
 [  4.4   3. ]
 [  5.1   3.4]
 [  5.    3.5]
 [  4.5   2.3]
 [  4.4   3.2]
 [  5.    3.5]
 [  5.1   3.8]
 [  4.8   3. ]
 [  5.1   3.8]
 [  4.6   3.2]
 [  5.3   3.7]
 [  5.    3.3]
 [  7.    3.2]
 [  6.4   3.2]
 [  6.9   3.1]
 [  5.5   2.3]
 [  6.5   2.8]
 [  5.7   2.8]
 [  6.3   3.3]
 [  4

In [254]:
# 3. Views vs Copies (Critical Concept)


sub_view = arr[:5, 0]       # likely a VIEW
sub_copy = arr[:5, 0].copy()  # explicit COPY

print("\nOriginal first element:", arr[0, 0])

# Modify view
sub_view[0] = 999.0

print("After modifying view:")
print("arr[0,0]:", arr[0, 0])  # may change → shared memory behavior

# Modify copy
sub_copy[0] = -999.0

print("\nAfter modifying copy:")
print("arr[0,0] (unchanged by copy):", arr[0, 0])



Original first element: 100.0
After modifying view:
arr[0,0]: 999.0

After modifying copy:
arr[0,0] (unchanged by copy): 999.0


In [255]:
# 4. Confirm Memory Sharing

print("\nBase sharing check:")
print("sub_view.base is arr:", sub_view.base is arr)
print("sub_copy.base is arr:", sub_copy.base is arr)


Base sharing check:
sub_view.base is arr: False
sub_copy.base is arr: False


##2.4) Reshaping of Arrays

Reshaping in NumPy refers to the process of reorganizing the structure of an array without changing its underlying data. This operation is essential when preparing data for computation, aligning dimensions for algorithms, or converting between vector and matrix representations.

The primary tool for reshaping is the `reshape()` method, which transforms an array into a new shape provided that the total number of elements remains unchanged. This constraint ensures that data integrity is preserved while only the structural layout is modified.

For example, a sequential range of values can be reorganized into a two-dimensional grid, illustrating how linear data can be structured into matrix form for analytical purposes.

A key point is that reshaping may sometimes return a view rather than a copy, depending on memory layout. However, this is not guaranteed in all cases, especially when the underlying data is not stored contiguously in memory.

A common practical transformation is converting a one-dimensional array into either:

- a row vector (1 × n structure), or  
- a column vector (n × 1 structure)

This can be achieved either through reshaping or by introducing a new axis using `newaxis`, which explicitly adds a dimension without altering the data.

These transformations are fundamental in data science workflows, particularly in linear algebra, machine learning preprocessing, and statistical modeling, where correct dimensional alignment is often required for computation.

In [256]:
import numpy as np


# Create 1D array from a feature column
vec = iris_df.iloc[:, 0].to_numpy()

print("Original shape:", vec.shape)
print("Original array (first 10):", vec[:10])


Original shape: (150,)
Original array (first 10): [999.    4.9   4.7   4.6   5.    5.4   4.6   5.    4.4   4.9]


In [257]:
# 1. Reshape into 2D matrix

# Ensure total elements remain unchanged
mat = vec.reshape(-1, 1)   # column matrix

print("\nReshaped to column vector:")
print("Shape:", mat.shape)
print(mat[:5])



Reshaped to column vector:
Shape: (150, 1)
[[999. ]
 [  4.9]
 [  4.7]
 [  4.6]
 [  5. ]]


In [258]:
# reshape into row-based structure (if compatible)
row_mat = vec.reshape(1, -1)

print("\nReshaped to row vector:")
print("Shape:", row_mat.shape)
print(row_mat[:, :5])


Reshaped to row vector:
Shape: (1, 150)
[[999.    4.9   4.7   4.6   5. ]]


In [259]:
# 2. Linear to matrix conversion

# Take multiple columns → 2D structure
multi = iris_df.iloc[:, :3].to_numpy()

print("\nOriginal 2D data shape:", multi.shape)

flat = multi.reshape(-1)  # flatten back to 1D

print("Flattened shape:", flat.shape)

re_mat = flat.reshape(multi.shape)

print("Restored shape:", re_mat.shape)



Original 2D data shape: (150, 3)
Flattened shape: (450,)
Restored shape: (150, 3)


In [260]:
# 3. Using newaxis for dimension expansion

col_vector = vec[:, np.newaxis]   # (n,1)
row_vector = vec[np.newaxis, :]    # (1,n)

print("\nnewaxis column shape:", col_vector.shape)
print("newaxis row shape:", row_vector.shape)



newaxis column shape: (150, 1)
newaxis row shape: (1, 150)


In [261]:
# 4. View vs Copy behavior

reshaped_view = vec.reshape(-1, 1)

print("\nBefore modification:", reshaped_view[0, 0])

reshaped_view[0, 0] = 999.0

print("After modification:")
print("Original vec[0]:", vec[0])  # may reflect change (view behavior)

# Explicit copy
reshaped_copy = vec.reshape(-1, 1).copy()
reshaped_copy[0, 0] = -999.0

print("\nCopy does NOT affect original:")
print("vec[0]:", vec[0])


Before modification: 999.0
After modification:
Original vec[0]: 999.0

Copy does NOT affect original:
vec[0]: 999.0


##2.5) Array Concatenation and Splitting

All of the preceding routines worked on single arrays. It is also possible to combine multiple arrays into one and, conversely, to split a single array into multiple arrays. These operations are essential when constructing datasets from modular components or when decomposing data for analysis.

---

## Concatenation of Arrays

Concatenation refers to joining two or more arrays into a single array. In NumPy, this is primarily achieved using `np.concatenate`, `np.vstack`, and `np.hstack`.

The function `np.concatenate` takes a tuple or list of arrays as its argument. For example, two one-dimensional arrays can be joined into a single sequence.

You can also concatenate more than two arrays at once by passing them together in a list.

For two-dimensional arrays, concatenation can be performed along different axes. When concatenating along the first axis, arrays are stacked vertically, effectively increasing the number of rows. When concatenating along the second axis, the arrays are joined horizontally, increasing the number of columns.

To simplify working with arrays of mixed dimensions, NumPy provides convenience functions:

- `np.vstack` stacks arrays vertically (row-wise), even when dimensions differ.  
- `np.hstack` stacks arrays horizontally (column-wise).  
- `np.dstack` stacks arrays along the third axis, useful for building higher-dimensional structures.  

These routines provide flexible mechanisms for constructing complex array structures from simpler components.

---

## Splitting of Arrays

The inverse operation of concatenation is splitting, which divides a single array into multiple subarrays. NumPy provides `np.split`, `np.hsplit`, and `np.vsplit` for this purpose.

The function `np.split` divides an array at specified indices. The split points are provided as a list, and the array is partitioned accordingly. If N split points are given, the result is N + 1 subarrays.

For two-dimensional arrays, specialized versions are often more intuitive:

- `np.vsplit` splits an array vertically (along rows), producing upper and lower partitions.  
- `np.hsplit` splits an array horizontally (along columns), producing left and right partitions.  
- `np.dsplit` performs splitting along the third axis for three-dimensional arrays.  

These functions are particularly useful in data preprocessing, where structured datasets must be divided into training, testing, or feature-specific components.

In [262]:
import numpy as np

X = iris_df.to_numpy()

# Split into two feature blocks
A = X[:, :2]   # first two columns
B = X[:, 2:]   # remaining columns

# 1. Concatenation (np.concatenate)

concat_axis0 = np.concatenate([A, B], axis=1)  # horizontal join
concat_axis1 = np.concatenate([A, B], axis=0)  # vertical join (requires same columns)

print("Original A shape:", A.shape)
print("Original B shape:", B.shape)

print("\nConcatenate axis=1 (columns):", concat_axis0.shape)
print("Concatenate axis=0 (rows):", concat_axis1.shape)


Original A shape: (150, 2)
Original B shape: (150, 2)

Concatenate axis=1 (columns): (150, 4)
Concatenate axis=0 (rows): (300, 2)


In [263]:
# 2. vstack, hstack, dstack

# Vertical stacking (row-wise)
vstacked = np.vstack([A, A])

# Horizontal stacking (column-wise)
hstacked = np.hstack([A, B])

# Depth stacking (3D construction)
dstacked = np.dstack([A, A])

print("\nVstack shape:", vstacked.shape)
print("Hstack shape:", hstacked.shape)
print("Dstack shape:", dstacked.shape)



Vstack shape: (300, 2)
Hstack shape: (150, 4)
Dstack shape: (150, 2, 2)


In [264]:
# 3. Splitting arrays (np.split)

split_points = [50, 100]

split_arrays = np.split(X, split_points, axis=0)

print("\nSplit results:")
for i, part in enumerate(split_arrays):
    print(f"Part {i} shape:", part.shape)



Split results:
Part 0 shape: (50, 4)
Part 1 shape: (50, 4)
Part 2 shape: (50, 4)


In [265]:
# 4. Vertical split

v_part = np.vsplit(X, 3)

print("\nVsplit into 3 parts:")
for i, part in enumerate(v_part):
    print(f"Part {i} shape:", part.shape)



Vsplit into 3 parts:
Part 0 shape: (50, 4)
Part 1 shape: (50, 4)
Part 2 shape: (50, 4)


In [266]:
# 5. Horizontal split

h_part = np.hsplit(X, 2)

print("\nHsplit into 2 parts:")
for i, part in enumerate(h_part):
    print(f"Part {i} shape:", part.shape)



Hsplit into 2 parts:
Part 0 shape: (150, 2)
Part 1 shape: (150, 2)


In [267]:
# 6. Reconstruction check

reconstructed = np.concatenate(h_part, axis=1)

print("\nReconstruction equal to original:", np.allclose(reconstructed, X))


Reconstruction equal to original: True
