<a href="https://colab.research.google.com/github/sethkipsangmutuba/Data-Visualization/blob/main/Session_A1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Introduction to NumPy

##Seth Kipsang

### Understanding Data Types in Python

#### A Python Integer Is More Than Just an Integer

#### A Python List Is More Than Just a List

### Fixed-Type Arrays in Python

### Creating Arrays from Python Lists

### Creating Arrays from Scratch

### NumPy Standard Data Types

##1)  Understanding Data Types in Python — Lecture Notes (No Code)

This section establishes a foundational distinction in computational thinking: how Python manages data internally compared to statically typed languages, and why this distinction is crucial for numerical computing and data science.

---

### a. Central Idea of the Section

The core purpose is to understand:

- How Python represents data in memory  
- Why its design favors flexibility over computational efficiency  

This becomes essential when later transitioning to high-performance numerical tools like NumPy.

---

### b. Static Typing vs Dynamic Typing

#### Static Typing (e.g., C, Java)

In statically typed systems:

- Every variable has an explicitly declared type  
- The type is fixed before execution  
- Memory layout is predictable and optimized  

This leads to:

- High computational efficiency  
- Low runtime overhead  
- Less flexibility  

#### Dynamic Typing (Python)

Python uses dynamic typing:

- Variables do not require explicit type declarations  
- Types are inferred during execution  
- A variable can change type over time  

This enables:

- High flexibility  
- Ease of use  
- Rapid prototyping  

But it introduces:

- Runtime type checking overhead  
- Additional memory cost per object  
- Reduced efficiency for large-scale numerical operations  

---

### c. Key Concept: Variables as Objects

A critical conceptual shift is required:

- In Python, variables are not raw storage locations—they reference full objects  

Each object includes:

- The actual value  
- Type information  
- Internal metadata used by the interpreter  

Thus, even a simple number is stored as a structured object, not a raw primitive value.

---

### d. Flexibility vs Performance Trade-off

Python’s design prioritizes usability:

- Variables can change type dynamically  
- Data structures can hold mixed types  

However, this flexibility comes at a cost:

- Every operation requires type resolution at runtime  
- Memory usage increases due to object overhead  
- Large-scale numerical computation becomes inefficient  

---

### e. Core Limitation Highlighted

The key limitation exposed in this section is:

- Python’s object-based design is not optimized for large-scale numerical computation  

This becomes especially visible when handling:

- Large datasets  
- Repeated numerical operations  
- High-dimensional arrays  

---

### f. Why This Matters for Data Science

In data science workflows, efficiency is critical. The overhead introduced by Python’s dynamic object system creates bottlenecks in:

- Statistical computation  
- Machine learning pipelines  
- Large-scale data processing  

---

### 7. Conceptual Transition to NumPy

This limitation motivates the need for NumPy, which introduces:

- Fixed-type numerical arrays  
- Contiguous memory storage  
- Reduced object overhead  

In [114]:
import time
import sys
import numpy as np
from sklearn.datasets import load_iris

# -----------------------------
# Load Built-in Dataset (Iris)
# -----------------------------
iris = load_iris()
iris

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

NumPy array (fixed-type, contiguous)

In [115]:
X_numpy = iris.data  # NumPy array (fixed-type, contiguous)
X_numpy

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

Convert to Python list (object-based structure)

In [116]:
X_list = X_numpy.tolist()

Demonstrating Dynamic Typing

In [117]:
x = 10          # integer
print("Type of x:", type(x))

x = 10.5        # float
print("Type of x after reassignment:", type(x))

x = "Iris"      # string
print("Type of x after reassignment:", type(x))


Type of x: <class 'int'>
Type of x after reassignment: <class 'float'>
Type of x after reassignment: <class 'str'>


Variables as Objects

In [118]:
a = 5
b = a

print("\nValue of a:", a)
print("Value of b:", b)
print("Memory address of a:", id(a))
print("Memory address of b:", id(b))



Value of a: 5
Value of b: 5
Memory address of a: 11645480
Memory address of b: 11645480


Performance Comparison

In [119]:
def sum_list(data):
    total = 0
    for row in data:
        for val in row:
            total += val
    return total

def sum_numpy(data):
    return np.sum(data)

# Time Python list computation
start = time.time()
list_result = sum_list(X_list)
list_time = time.time() - start
list_time

0.00024080276489257812

In [120]:
# Time NumPy computation
start = time.time()
numpy_result = sum_numpy(X_numpy)
numpy_time = time.time() - start
numpy_time

0.0008101463317871094

In [121]:
numpy_time = time.time() - start
numpy_time

0.009252309799194336

Memory Comparison

In [122]:
list_memory = sys.getsizeof(X_list)
list_memory

1256

In [123]:
numpy_memory = X_numpy.nbytes
numpy_memory

4800

##1.1)  A Python Integer Is More Than Just an Integer

In Python, an integer is not a simple raw value but a high-level object implemented through an underlying C structure.

It stores not only the numeric value but also metadata such as:
- reference counting (for memory management)
- type information
- object size
- internal digit representation of the integer value

This object-based design enables Python’s flexibility and dynamic behavior, allowing integers to seamlessly integrate into a unified object system.

However, this abstraction introduces both computational and memory overhead compared to low-level languages like C, where integers are stored as fixed-size primitive values with minimal metadata.

As a result, large-scale numerical computations involving many Python integers are less memory-efficient and slower in aggregate operations.

This limitation motivates the use of optimized array-based structures such as NumPy, where numerical values are stored in contiguous, fixed-type memory blocks with significantly reduced overhead.

In [124]:
# Convert sklearn Bunch → DataFrame

iris_df = pd.DataFrame(
    data=iris.data,
    columns=iris.feature_names
)

# 1. Integer Representation

int_series = (iris_df.iloc[:, 0] * 100).astype(int)

int_list = int_series.tolist()
int_numpy = int_series.to_numpy()


# 2. Python Integer Object Inspection

x = int_list[0]

print("Value:", x)
print("Type:", type(x))
print("Memory size of Python int:", sys.getsizeof(x), "bytes")

Value: 509
Type: <class 'int'>
Memory size of Python int: 28 bytes


In [125]:
# 3. NumPy Integer Inspection

np_val = int_numpy[0]

print("\nNumPy value:", np_val)
print("NumPy dtype:", int_numpy.dtype)
print("Memory per element:", int_numpy.itemsize, "bytes")


NumPy value: 509
NumPy dtype: int64
Memory per element: 8 bytes


In [126]:
# 4. Memory Comparison

list_memory = sys.getsizeof(int_list) + sum(sys.getsizeof(i) for i in int_list)
numpy_memory = int_numpy.nbytes

print("\nMemory Usage:")
print("Python list:", list_memory, "bytes")
print("NumPy array:", numpy_memory, "bytes")


Memory Usage:
Python list: 5456 bytes
NumPy array: 1200 bytes


In [127]:
# 5. Computation Timing

def sum_list(data):
    total = 0
    for v in data:
        total += v
    return total

start = time.time()
list_sum = sum_list(int_list)
list_time = time.time() - start

start = time.time()
numpy_sum = np.sum(int_numpy)
numpy_time = time.time() - start

print("\nSum (List):", list_sum)
print("Sum (NumPy):", numpy_sum)

print("\nExecution Time:")
print("List:", list_time)
print("NumPy:", numpy_time)


Sum (List): 87637
Sum (NumPy): 87637

Execution Time:
List: 8.678436279296875e-05
NumPy: 0.00012612342834472656


##1.2 A Python List Is More Than Just a List

A Python list is a flexible, mutable container that can store multiple Python objects of potentially different types. This flexibility arises from Python’s dynamic typing, where each element in a list is a full Python object carrying its own metadata such as type information and reference count.

While this design allows heterogeneous collections (for example integers, strings, and floats in the same list), it introduces overhead because each element is independently managed as a complete object.

Internally, a Python list does not store raw values directly; instead, it stores references (pointers) to separate objects distributed in memory.

This structure contrasts with fixed-type arrays, such as those in NumPy, which store data in a single contiguous memory block with uniform type information. As a result, lists prioritize flexibility, while fixed-type arrays prioritize efficiency in memory usage and computational speed especially important in large scale data science and numerical computation contexts.

In [128]:
import numpy as np
import pandas as pd

# Create a heterogeneous Python list from Iris data
# (int, float, string mixed structure to show flexibility)

python_list = [
    iris_df.iloc[0, 0],              # float
    int(iris_df.iloc[0, 1] * 100),   # int
    "iris_sample",                   # string
    iris_df.iloc[0, 2]               # float
]


# 1. Inspect List Structure

print("Python List:", python_list)

for i, item in enumerate(python_list):
    print(f"Element {i}: value={item}, type={type(item)}, size={sys.getsizeof(item)} bytes")

Python List: [np.float64(5.1), 350, 'iris_sample', np.float64(1.4)]
Element 0: value=5.1, type=<class 'numpy.float64'>, size=32 bytes
Element 1: value=350, type=<class 'int'>, size=28 bytes
Element 2: value=iris_sample, type=<class 'str'>, size=52 bytes
Element 3: value=1.4, type=<class 'numpy.float64'>, size=32 bytes


In [129]:
# 2. Memory of List Container vs Elements

list_container_size = sys.getsizeof(python_list)
elements_size = sum(sys.getsizeof(item) for item in python_list)

print("\nList container size:", list_container_size, "bytes")
print("Sum of element sizes:", elements_size, "bytes")



List container size: 88 bytes
Sum of element sizes: 144 bytes


In [130]:
# 3. Contrast with NumPy Array (fixed-type)

numeric_array = iris_df.iloc[:, 0].to_numpy()

print("\nNumPy dtype:", numeric_array.dtype)
print("NumPy itemsize:", numeric_array.itemsize, "bytes per element")
print("Total NumPy memory:", numeric_array.nbytes, "bytes")


NumPy dtype: float64
NumPy itemsize: 8 bytes per element
Total NumPy memory: 1200 bytes


In [131]:
# 4. Demonstrate Heterogeneity vs Homogeneity

try:
    # This works for list (heterogeneous allowed)
    python_list.append({"new_type": "dictionary"})
    print("\nList after adding dict:", python_list[-1])
except Exception as e:
    print(e)

# NumPy strict typing behavior
try:
    numeric_array = np.append(numeric_array, "text")  # forces type upcast
    print("\nNumPy array after appending string:", numeric_array[-1])
    print("New dtype:", numeric_array.dtype)
except Exception as e:
    print(e)


List after adding dict: {'new_type': 'dictionary'}

NumPy array after appending string: text
New dtype: <U32


##1.3) Fixed-Type Arrays in Python

Python provides multiple mechanisms for storing data in fixed-type, memory-efficient structures where all elements share the same data type. This design reduces overhead compared to standard Python lists, which store references to full Python objects.

One built-in option is the `array` module, which allows creation of dense arrays with a specified uniform type using type codes (for example, integers). These arrays are more memory-efficient than lists because they store raw values rather than object references.

However, their functionality is limited compared to NumPy arrays. The **NumPy ndarray** extends this idea significantly by combining fixed-type storage with highly optimized numerical operations, enabling fast computation over large datasets.

NumPy is typically imported under a standard alias for convenience, forming the foundation for most scientific computing workflows in Python.

In [132]:
import array

numeric_col = iris_df.iloc[:, 0]

# 1. Python List (object-based)

py_list = numeric_col.tolist()

In [133]:
# 2. Built-in array module (fixed-type)

# 'd' = double precision float
py_array = array.array('d', numeric_col)

In [134]:
# 3. NumPy array (optimized fixed-type)

np_array = numeric_col.to_numpy()


In [135]:
# 4. Memory Comparison

print("\n--- Memory Usage ---")

list_memory = sys.getsizeof(py_list) + sum(sys.getsizeof(x) for x in py_list)
array_memory = sys.getsizeof(py_array)
numpy_memory = np_array.nbytes

print("Python list:", list_memory, "bytes")
print("array module:", array_memory, "bytes")
print("NumPy array:", numpy_memory, "bytes")



--- Memory Usage ---
Python list: 4856 bytes
array module: 1392 bytes
NumPy array: 1200 bytes


In [136]:
# 5. Type Uniformity Check

print("\n--- Type Inspection ---")

print("array module type:", py_array.typecode)
print("NumPy dtype:", np_array.dtype)

print("First element types:")
print("List:", type(py_list[0]))
print("array:", type(py_array[0]))
print("NumPy:", type(np_array[0]))


--- Type Inspection ---
array module type: d
NumPy dtype: float64
First element types:
List: <class 'float'>
array: <class 'float'>
NumPy: <class 'numpy.float64'>


In [137]:
# 6. Computation Performance

import time

def sum_list(data):
    total = 0
    for v in data:
        total += v
    return total

# List timing
start = time.time()
sum_list(py_list)
list_time = time.time() - start

# array module timing
start = time.time()
sum(py_array)
array_time = time.time() - start

# NumPy timing
start = time.time()
np.sum(np_array)
numpy_time = time.time() - start

print("\n--- Computation Time ---")
print("List:", list_time)
print("array module:", array_time)
print("NumPy:", numpy_time)


--- Computation Time ---
List: 0.00012564659118652344
array module: 0.00011205673217773438
NumPy: 0.0002586841583251953


##1.4) Creating Arrays from Python Lists

NumPy arrays can be directly constructed from Python lists using a unified array constructor. This provides a bridge between Python’s flexible list structures and NumPy’s efficient fixed-type numerical arrays.

A key distinction is that NumPy arrays enforce homogeneity: all elements must share a single data type. When mixed types are provided, NumPy applies type upcasting, converting values into a common compatible type (for example, integers may be promoted to floating-point numbers).

If required, the data type can be explicitly defined using the `dtype` parameter, allowing precise control over memory representation and numerical precision.

Beyond one-dimensional structures, NumPy naturally supports multidimensional arrays. Nested Python lists are interpreted as rows in a matrix-like structure, enabling direct creation of 2D arrays without additional transformation. This forms the foundation for higher-dimensional data modeling in scientific computing and data science workflows.

In [138]:
# 1. Creating NumPy Array from Python List

python_list = iris_df.iloc[:, 0].tolist()

np_array = np.array(python_list)

print("Original Python list (first 5):", python_list[:5])
print("NumPy array (first 5):", np_array[:5])

Original Python list (first 5): [5.1, 4.9, 4.7, 4.6, 5.0]
NumPy array (first 5): [5.1 4.9 4.7 4.6 5. ]


In [139]:
# 2. Type Homogeneity + Upcasting

mixed_list = [1, 2, 3.5, 4, 5]

mixed_array = np.array(mixed_list)

print("\nMixed Python list:", mixed_list)
print("NumPy array:", mixed_array)
print("NumPy dtype (after upcasting):", mixed_array.dtype)



Mixed Python list: [1, 2, 3.5, 4, 5]
NumPy array: [1.  2.  3.5 4.  5. ]
NumPy dtype (after upcasting): float64


In [140]:
# 3. Explicit dtype Control

int_array = np.array(mixed_list, dtype=np.int32)

print("\nExplicit dtype (int32):", int_array)
print("dtype:", int_array.dtype)

float_array = np.array(mixed_list, dtype=np.float64)

print("Explicit dtype (float64):", float_array)
print("dtype:", float_array.dtype)



Explicit dtype (int32): [1 2 3 4 5]
dtype: int32
Explicit dtype (float64): [1.  2.  3.5 4.  5. ]
dtype: float64


In [141]:
# 4. Multidimensional Arrays from Nested Lists

nested_list = iris_df.iloc[:5, :3].values.tolist()

matrix = np.array(nested_list)

print("\nNested Python list (first 2 rows):", nested_list[:2])
print("\nNumPy 2D array:\n", matrix)

print("\nShape:", matrix.shape)
print("Dimensionality:", matrix.ndim)


Nested Python list (first 2 rows): [[5.1, 3.5, 1.4], [4.9, 3.0, 1.4]]

NumPy 2D array:
 [[5.1 3.5 1.4]
 [4.9 3.  1.4]
 [4.7 3.2 1.3]
 [4.6 3.1 1.5]
 [5.  3.6 1.4]]

Shape: (5, 3)
Dimensionality: 2


## Creating Arrays from Scratch

NumPy provides a rich set of built-in functions for constructing arrays directly from defined patterns, which is especially efficient for large scale data initialization and simulation tasks.

These constructors allow users to generate arrays with specific structures without manually populating elements:

**Constant arrays:** Arrays filled entirely with zeros, ones, or any fixed value are commonly used for initialization, baseline modeling, and placeholders.

**Sequential arrays:** Evenly spaced numeric sequences can be generated over a defined interval, supporting controlled sampling and feature generation.

**Linearly spaced arrays:** Values can be distributed uniformly between endpoints, which is particularly useful in numerical analysis and plotting.

**Random arrays:** NumPy supports both uniform and normal distributions, enabling stochastic simulation, Monte Carlo methods, and statistical modeling.

**Integer random arrays:** Useful for discrete simulations, sampling, and algorithm testing.

**Identity matrices:** Fundamental in linear algebra, representing neutral transformation operators.

**Uninitialized arrays:** Allocate memory without setting values, offering performance benefits when values will be overwritten immediately.

These methods highlight NumPy’s focus on computational efficiency and flexibility, allowing direct construction of structured numerical data essential for scientific computing workflows.

In [142]:
# 1. Constant Arrays

zeros_array = np.zeros((3, 4))
ones_array = np.ones((3, 4))
full_array = np.full((3, 4), 7)

print("Zeros:\n", zeros_array)
print("\nOnes:\n", ones_array)
print("\nFull (7):\n", full_array)


Zeros:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

Ones:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

Full (7):
 [[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]


In [143]:
# 2. Sequential Arrays

seq_array = np.arange(0, 10, 2)

print("\nSequential (arange):", seq_array)


Sequential (arange): [0 2 4 6 8]


In [144]:
# 3. Linearly Spaced Arrays

lin_array = np.linspace(0, 1, 5)

print("\nLinearly spaced (linspace):", lin_array)



Linearly spaced (linspace): [0.   0.25 0.5  0.75 1.  ]


In [145]:
# 4. Random Arrays (Uniform & Normal)

uniform_random = np.random.rand(3, 3)
normal_random = np.random.randn(3, 3)

print("\nUniform random:\n", uniform_random)
print("\nNormal random:\n", normal_random)



Uniform random:
 [[0.39978256 0.99416289 0.06646424]
 [0.5476576  0.17572629 0.22179884]
 [0.17903957 0.18933623 0.01342368]]

Normal random:
 [[-0.03809172  0.11174776 -0.25407918]
 [ 1.52811201  0.95978248  0.14009954]
 [ 1.03410876 -1.91243267  1.21996894]]


In [146]:
# 5. Integer Random Arrays

int_random = np.random.randint(0, 10, size=(3, 3))

print("\nInteger random:\n", int_random)



Integer random:
 [[9 4 1]
 [5 7 0]
 [1 9 7]]


In [147]:
# 6. Identity Matrix

identity = np.eye(4)

print("\nIdentity matrix:\n", identity)


Identity matrix:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [148]:

# 7. Uninitialized Array

empty_array = np.empty((3, 3))

print("\nUninitialized array:\n", empty_array)


Uninitialized array:
 [[3.5e-323 2.0e-323 4.0e-323]
 [4.0e-323 2.5e-323 9.9e-324]
 [1.5e-323 9.9e-324 3.0e-323]]


##1.5) NumPy Standard Data Types

NumPy arrays are fundamentally homogeneous, meaning every element must share the same data type. This design ensures computational efficiency and predictable memory usage, but it also requires careful attention to data type selection.

Because NumPy is implemented in C, its data types closely mirror low-level machine representations, including fixed-size integers, floating-point numbers, unsigned integers, and complex numbers. These types differ in memory footprint and numerical range, which directly affects precision, performance, and storage efficiency.

When creating arrays, data types can be explicitly defined either through string identifiers or NumPy’s built-in type objects. This allows precise control over how data is stored and processed, which is especially important in large-scale numerical computation, statistical modeling, and scientific analysis.

More advanced type systems, including structured and compound types, extend NumPy’s capability beyond simple numerical arrays, forming a bridge toward relational and heterogeneous data representations used later in scientific workflows.

In [149]:
import numpy as np

col = iris_df.iloc[:, 0]


# 1. Default dtype inference

default_array = np.array(col)

print("Default dtype:", default_array.dtype)


Default dtype: float64


In [150]:
# 2. Explicit numeric types

float32_array = np.array(col, dtype=np.float32)
float64_array = np.array(col, dtype=np.float64)

int32_array = np.array(col, dtype=np.int32)
uint8_array = np.array(col, dtype=np.uint8)

print("\nFloat32 dtype:", float32_array.dtype)
print("Float64 dtype:", float64_array.dtype)
print("Int32 dtype:", int32_array.dtype)
print("UInt8 dtype:", uint8_array.dtype)



Float32 dtype: float32
Float64 dtype: float64
Int32 dtype: int32
UInt8 dtype: uint8


In [151]:
# 3. Memory footprint comparison

print("\n--- Memory per array ---")

print("float32 total bytes:", float32_array.nbytes)
print("float64 total bytes:", float64_array.nbytes)
print("int32 total bytes:", int32_array.nbytes)
print("uint8 total bytes:", uint8_array.nbytes)



--- Memory per array ---
float32 total bytes: 600
float64 total bytes: 1200
int32 total bytes: 600
uint8 total bytes: 150


In [152]:
# 4. Precision consequences

print("\n--- Precision example ---")

print("Original value:", col.iloc[0])
print("float32:", float32_array[0])
print("float64:", float64_array[0])
print("int32:", int32_array[0])



--- Precision example ---
Original value: 5.1
float32: 5.1
float64: 5.1
int32: 5


In [153]:
# 5. Complex numbers (extended type system)

complex_array = np.array(col, dtype=np.complex128)

print("\nComplex dtype:", complex_array.dtype)
print("Example value:", complex_array[0])



Complex dtype: complex128
Example value: (5.1+0j)


In [154]:
# 6. Structured dtype

structured = np.array(
    list(zip(
        iris_df.iloc[:, 0],
        iris_df.iloc[:, 1]
    )),
    dtype=[('feature1', 'f8'), ('feature2', 'f8')]
)

print("\nStructured dtype:", structured.dtype)
print("First element:", structured[0])


Structured dtype: [('feature1', '<f8'), ('feature2', '<f8')]
First element: (5.1, 3.5)
